
task 'start depending (Dep) Release', {
  description = ''
  advancedMode = '0'
  allowOutOfOrderRun = '0'
  alwaysRun = '0'
  enabled = '1'
  errorHandling = 'stopOnError'
  insertRollingDeployManualStep = '0'
  projectName = 'myFourBank'
  resourceName = ''
  skippable = '0'
  subErrorHandling = 'continueOnError'
  subproject = 'myFourBank'
  subrelease = 'nestDep'
  taskType = 'RELEASE'
  triggerType = 'async'
  useApproverAcl = '0'
  waitForPlannedStartDate = '0'
}
